pub mod app;
pub mod css;
pub mod event;
pub mod layout;
pub mod reactive;
pub mod terminal;
pub mod testing;
pub mod widget;
pub mod worker;

pub use app::App;
pub use event::AppEvent;
pub use testing::TestApp;
pub use testing::pilot::Pilot;
pub use widget::{Widget, WidgetId};
// Re-export proc macros — derive macro Widget lives in a separate namespace from the Widget trait,
// so `pub use textual_rs_macros::Widget` does not conflict with `pub use widget::Widget`.
pub use textual_rs_macros::Widget;
pub use textual_rs_macros::widget_impl;
pub use widget::label::Label;
pub use widget::button::{Button, ButtonVariant};
pub use widget::checkbox::Checkbox;
pub use widget::switch::Switch;
pub use widget::input::Input;
pub use widget::radio::{RadioButton, RadioSet};
pub use widget::text_area::TextArea;
pub use widget::select::Select;
pub use widget::layout::{Vertical, Horizontal};
pub use widget::header::Header;
pub use widget::footer::Footer;
pub use widget::placeholder::Placeholder;
pub use widget::progress_bar::ProgressBar;
pub use widget::sparkline::Sparkline;
pub use widget::list_view::ListView;
pub use widget::log::Log;
pub use widget::scroll_view::ScrollView;
pub use widget::data_table::{DataTable, ColumnDef};
pub use widget::tree_view::{Tree, TreeNode};
pub use widget::tabs::{Tabs, TabbedContent};
pub use widget::collapsible::Collapsible;
pub use widget::markdown::Markdown;
pub use worker::WorkerResult;
